# Generated by Django 4.2.2 on 2023-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_salesorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
